import os
from dotenv import load_dotenv

load_dotenv()

DB_PATH = os.getenv("LAUNCH_COMMAND_DB_PATH", "data/mcc.db")
PORT = int(os.getenv("LAUNCH_COMMAND_PORT", "5050"))

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
CONVERTKIT_API_SECRET = os.getenv("CONVERTKIT_API_SECRET")
INSTANTLY_API_KEY = os.getenv("INSTANTLY_API_KEY")
GA4_CREDENTIALS_PATH = os.getenv("GA4_CREDENTIALS_PATH") or os.getenv("GOOGLE_ANALYTICS_KEY_FILE")
GA4_PROPERTY_ID = os.getenv("GA4_PROPERTY_ID")
BUFFER_ACCESS_TOKEN = os.getenv("BUFFER_ACCESS_TOKEN")
STRIPE_API_KEY = os.getenv("STRIPE_API_KEY")
META_ADS_ACCESS_TOKEN = os.getenv("META_ADS_ACCESS_TOKEN")
REDDIT_ADS_TOKEN = os.getenv("REDDIT_ADS_TOKEN")
GOOGLE_ADS_CREDENTIALS = os.getenv("GOOGLE_ADS_CREDENTIALS")
SPARKLOOP_API_KEY = os.getenv("SPARKLOOP_API_KEY")
RAILWAY_API_KEY = os.getenv("RAILWAY_API_KEY")
YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY")
YOUTUBE_CHANNEL_ID = os.getenv("YOUTUBE_CHANNEL_ID")
HUNTER_API_KEY = os.getenv("HUNTER_API_KEY")
REDDIT_USERNAME = os.getenv("REDDIT_USERNAME")

# Alert & Monitoring
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")
HEALTHCHECKS_PING_URL = os.getenv("HEALTHCHECKS_PING_URL")  # e.g. https://hc-ping.com/<uuid>
